// import 'bootstrap/dist/css/bootstrap.min.css';
import '../../public/dist/css/style.min.css';
// import '../../public/assets/libs/chartist/dist/chartist.min.css';
// import '../../public/assets/libs/chartist-plugin-tooltips/dist/chartist-plugin-tooltip.css';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

import 'leaflet/dist/leaflet.css';
// import BootstrapClient from '@/app/components/BootStrapClient';
import './global.css';
// import Script from 'next/script';

import { Lexend } from 'next/font/google';
import React from 'react';
import SideBarContainer from '@/app/containers/SideBarContainer';
import Header from '@/app/components/organisms/Header';
// import useGlobalStore from '@/app/store/GlobalStore';

const lexend = Lexend({
  subsets: ['latin-ext'],
  weight: ['200', '300', '700'],
  variable: '--font-lexend',
});

export const metadata = {
  title: 'SEDP Dashboard',
  description: 'Generated by Next.js',
};

type Props = {
  children: React.ReactNode;
};

export default function RootLayout(props: Props) {
  return (
    <html lang="ko">
      <body className={`${lexend.variable} no-scrollbar tw-font-sans tw-antialiased`}>
        <Header />
        <SideBarContainer />
        {props.children}
        {/* <BootstrapClient /> */}
        {/* <Script src="/assets/libs/jquery/dist/jquery.min.js" /> */}
        <ToastContainer />
      </body>
    </html>
  );
}
