import '../../public/dist/css/style.min.css';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

import 'leaflet/dist/leaflet.css';
import './global.css';

import { Lexend } from 'next/font/google';
import React from 'react';
import SideBarContainer from '@/app/containers/SideBarContainer';
import BreadcrumbContainer from './containers/BreadcrumbContainer';
import { MSWComponent } from './components/settings/MSWComponent';
// import Script from 'next/script';

const lexend = Lexend({
  subsets: ['latin-ext'],
  weight: ['200', '300', '700'],
  variable: '--font-lexend',
});

export const metadata = {
  title: 'Lumir SEDP Dashboard',
  description: 'Generated by Next.js',
};

type Props = {
  children: React.ReactNode;
};

export default function RootLayout(props: Props) {
  return (
    <html lang="ko">
      <link rel="icon" href="/assets/images/favicon.png" type="image/png" />
      {/* Data Table CSS */}
      {/* <link
          rel="stylesheet"
          href="https://cdn.datatables.net/1.13.5/css/dataTables.bootstrap5.min.css"
        /> */}
      {/* Font Awesome CSS */}
      {/* <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css"
        /> */}
      <body className={`${lexend.variable} no-scrollbar tw-font-sans tw-antialiased`}>
        <MSWComponent />
        <BreadcrumbContainer />
        <SideBarContainer />
        {props.children}
        <ToastContainer />
        {/* <Script src="https://code.jquery.com/jquery-3.7.0.js" />
        <Script src="https://cdn.datatables.net/1.13.5/js/jquery.dataTables.min.js" />
        <Script src="https://cdn.datatables.net/responsive/2.1.0/js/dataTables.responsive.min.js" />
        <Script src="https://cdn.datatables.net/1.13.5/js/dataTables.bootstrap5.min.js" />
        <Script src="/table/js/script.js" /> */}
      </body>
    </html>
  );
}
