import "bootstrap/dist/css/bootstrap.min.css";
import "@/app/styles/css/style.css";
import "leaflet/dist/leaflet.css";
import BootstrapClient from "@/app/components/BootStrapClient";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body>
        {children}
        <BootstrapClient />
      </body>
    </html>
  );
}
