export enum UsgsStatusEnum {
  COLLECTING = 'COLLECTING',
  COLLECTING1 = 'COLLECTING-1',
  STOPPED = 'STOPPED',
  WAITING = 'WAITING',
  ACTIVE = 'ACTIVE',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  PAUSED = 'PAUSED',
}
